# Generated by Django 4.0.4 on 2022-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pointofsale_country_pointofsale_region_and_more'),
        ('administration', '0002_filter_value_filterby'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='point_of_sales',
            field=models.ManyToManyField(to='store.pointofsale'),
        ),
    ]
