# Generated by Django 4.0.4 on 2022-10-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_city_zone_remove_countryzone_region_and_more'),
        ('administration', '0003_role_point_of_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='locations.country'),
        ),
    ]
