# Generated by Django 4.0.4 on 2022-10-28 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='personal_phone',
            field=models.TextField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_phone',
            field=models.TextField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='viewslog',
            name='accounts',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='viewslog',
            name='country_id',
            field=models.TextField(default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='viewslog',
            name='divisions',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='viewslog',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='viewslog',
            name='roles',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamleader', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teammember', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
