# Generated by Django 4.0.4 on 2022-11-07 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_remove_viewslog_country_id_viewslog_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='administration.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='administration.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='administration.jobposition'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='team_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teammember', to=settings.AUTH_USER_MODEL),
        ),
    ]
