# Generated by Django 4.0.4 on 2022-11-07 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_user_company_user_department_user_job_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamleader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='team_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teammember', to=settings.AUTH_USER_MODEL),
        ),
    ]
