# Generated by Django 4.0.4 on 2022-11-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_userstatuslog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatuslog',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
