# Generated by Django 4.0.4 on 2022-11-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country_latitude_country_longitude'),
        ('administration', '0013_alter_userstatuslog_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatuslog',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to='locations.country'),
        ),
    ]
