# Generated by Django 4.0.4 on 2022-12-19 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0004_view_country_view_division_view_group1'),
        ('administration', '0014_alter_userstatuslog_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewSharingAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_sharing_acc', to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_sharing_acc', to='views.view')),
            ],
        ),
    ]
