# Generated by Django 4.0.4 on 2022-07-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfSaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50, unique=True)),
                ('gscn_site_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('mso_name', models.CharField(default='mso_default_name', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofsale', to='store.account')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofsale', to='locations.city')),
                ('pos_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofsale', to='store.pointofsaletype')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofsale', to='store.segment')),
            ],
        ),
    ]
