# Generated by Django 4.0.4 on 2022-08-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofsale', to='locations.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofsale', to='locations.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofsale', to='locations.countryzone'),
            preserve_default=False,
        ),
    ]
