# Generated by Django 4.0.4 on 2022-09-21 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pointofsale_country_pointofsale_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='custom_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_pointofsale', to='store.account'),
            preserve_default=False,
        ),
    ]
