# Generated by Django 4.0.4 on 2022-09-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_pointofsale_custom_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=50, unique=True)),
                ('custom', models.CharField(max_length=50)),
            ],
        ),
    ]
