# Generated by Django 4.0.4 on 2022-07-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0002_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flooring',
            name='point_of_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flooring', to='store.pointofsale'),
        ),
        migrations.AddField(
            model_name='flooring',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flooring', to='product.product'),
        ),
        migrations.AddField(
            model_name='flooring',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flooring', to='product.week'),
        ),
        migrations.AlterUniqueTogether(
            name='flooring',
            unique_together={('week', 'product', 'point_of_sale')},
        ),
    ]
