# Generated by Django 4.0.4 on 2022-10-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerOneBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamo_id', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('started_time', models.IntegerField(default=0)),
                ('ended_time', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LayerOneURI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorCPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ip', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorRAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ip', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='LayerOneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_time', models.IntegerField(default=0)),
                ('ended_time', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_one_batch', to='reports.layeronebatch')),
            ],
        ),
        migrations.AddField(
            model_name='layeronebatch',
            name='uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_one_uri', to='reports.layeroneuri'),
        ),
    ]
