# Generated by Django 4.0.4 on 2022-10-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_layeronebatch_ended_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcpu',
            name='env',
            field=models.CharField(default='local', max_length=5),
        ),
        migrations.AddField(
            model_name='monitorram',
            name='env',
            field=models.CharField(default='local', max_length=5),
        ),
    ]
