# Generated by Django 4.0.4 on 2022-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_layeronebatch_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeroneprogress',
            name='item',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layeroneprogress',
            name='redis_key',
            field=models.CharField(default='key', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layeroneprogress',
            name='status_code',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
