# Generated by Django 4.0.4 on 2022-10-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_layeroneprogress_item_layeroneprogress_redis_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layeroneprogress',
            name='batch',
        ),
        migrations.CreateModel(
            name='LayerOneLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('ended_time', models.DateTimeField(null=True)),
                ('progress', models.IntegerField()),
                ('size', models.PositiveSmallIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_one_batch', to='reports.layeronebatch')),
            ],
        ),
        migrations.AddField(
            model_name='layeroneprogress',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='layer_one_lot', to='reports.layeronelot'),
            preserve_default=False,
        ),
    ]
