# Generated by Django 4.0.4 on 2022-11-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_reportsframes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportsFrames',
            new_name='PowerBI',
        ),
    ]
