# Generated by Django 4.0.4 on 2022-08-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='countryzone',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
    ]
