# Generated by Django 4.0.4 on 2022-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_city_zone_remove_countryzone_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14),
        ),
    ]
