# Generated by Django 4.0.4 on 2022-11-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
