# Generated by Django 4.0.4 on 2022-11-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country_latitude_country_longitude'),
        ('product', '0002_initial'),
        ('views', '0003_alter_view_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view', to='locations.country'),
        ),
        migrations.AddField(
            model_name='view',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view', to='product.division'),
        ),
        migrations.AddField(
            model_name='view',
            name='group1',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
